modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "required"
versionRange = "[19.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "myotus"
type = "required"
versionRange = "[${myotus_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2wtlib"
type = "required"
versionRange = "[19.5.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extendedcrafting"
type = "optional"
versionRange = "[7.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extendedae"
type = "optional"
versionRange = "[1.21-2.2.29-neoforge,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extendedae_plus"
type = "optional"
versionRange = "[1.21.1-1.5.4.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "advanced_ae"
type = "optional"
versionRange = "[1.6.11-1.21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "avaritia"
type = "optional"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type = "optional"
ordering = "AFTER"
side = "BOTH"
