org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

java_version=25
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.100
neo_version_range=[26.1.2.100,26.2)
loader_version_range=[6,)
mod_loader=neoforge
mod_version_type=beta
mod_id=extendedmolecularassembler
mod_name=Extended Molecular Assembler
mod_license=LGPL-3.0
mod_version=26.0.0-SNAPSHOT
mod_group_id=me.myogoo
mod_authors=myogoo
mod_description=Adds AE2 crafting machines and terminals for larger table recipes.

myotus_version=26.0.0
AE2_version=26.1.10-beta
AE2WTLib_version=26.1.1-beta
guideme_version=26.1.12-beta
JEI_version=29.33.0.87
Cucumber_version=26.1.2-9.0.0
ExtendedCrafting_version=26.1.2-8.0.1
ReAvaritia_version=26.1.2-1.4.2-release
ExtendedAE_version=26.1-1.0.4-neoforge
ExtendedAE_file=8698967
AdvancedAE_version=26.1.7
Glodium_version=26.1-1.2-neoforge

enable_excrafting=true
enable_ae2wtlib=true
enable_extendedae=true
enable_advancedae=true
enable_avaritia=re
itemListMod=jei
