buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version.toString()))
}

base {
    archivesName = "ExtendedMolecularAssembler-${minecraft_version}"
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly fg.deobf("me.myogoo:myotus:${myotus_version}")
    compileOnly fg.deobf("appeng:appliedenergistics2-forge:${AE2_version}")
    compileOnly fg.deobf("org.appliedenergistics:guideme:${guideME_version}:api")
    compileOnly fg.deobf("maven.modrinth:applied-energistics-2-wireless-terminals:${AE2WTLib_version}")

    runtimeOnly fg.deobf("me.myogoo:myotus:${myotus_version}")
    runtimeOnly fg.deobf("appeng:appliedenergistics2-forge:${AE2_version}")
    runtimeOnly fg.deobf("org.appliedenergistics:guideme:${guideME_version}")
    runtimeOnly fg.deobf("maven.modrinth:applied-energistics-2-wireless-terminals:${AE2WTLib_version}")

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${JEI_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${JEI_version}")
    compileOnly fg.deobf("maven.modrinth:extended-crafting:${ExtendedCrafting_version}")
    compileOnly fg.deobf("maven.modrinth:cucumber:${Cucumber_version}")
    compileOnly fg.deobf("maven.modrinth:extended-ae:${ExtendedAE_version}")
    compileOnly fg.deobf("maven.modrinth:glodium:${Glodium_version}")
    compileOnly fg.deobf("maven.modrinth:avaritianeo:${AvaritiaNeo_version}")
    compileOnly fg.deobf("maven.modrinth:re-avaritia:${ReAvaritia_version}")

    if (project.itemListMod == 'jei') {
        runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${JEI_version}")
    }

    if (project.enable_excrafting == 'true') {
        runtimeOnly fg.deobf("maven.modrinth:extended-crafting:${ExtendedCrafting_version}")
        runtimeOnly fg.deobf("maven.modrinth:cucumber:${Cucumber_version}")
    }

    if (project.enable_extendedae == 'true') {
        runtimeOnly fg.deobf("maven.modrinth:extended-ae:${ExtendedAE_version}")
        runtimeOnly fg.deobf("maven.modrinth:glodium:${Glodium_version}")
    }

    switch (project.enable_avaritia) {
        case 'neo':
            runtimeOnly fg.deobf("maven.modrinth:avaritianeo:${AvaritiaNeo_version}")
            break
        case 're':
            runtimeOnly fg.deobf("maven.modrinth:re-avaritia:${ReAvaritia_version}")
            break
        case 'none':
            break
        default:
            throw new GradleException("Invalid value for enable_avaritia: ${project.enable_avaritia}")
    }
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            myotus_version         : myotus_version
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version.toString(),
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            groupId = project.mod_group_id
            artifactId = project.mod_id
            version = project.mod_version
            artifact jar
        }
    }
    repositories {
        maven {
            name = 'projectLocal'
            url = rootProject.layout.projectDirectory.dir('repo').asFile.toURI()
        }
    }
}
